// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/account-deletion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account-deletion">> = Specific
  const handler = {} as typeof import("../../../src/app/account-deletion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin-session-expired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-session-expired">> = Specific
  const handler = {} as typeof import("../../../src/app/admin-session-expired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/access-monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/access-monitor">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/access-monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/account-deletion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/account-deletion">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/account-deletion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/account-memberships/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/account-memberships">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/account-memberships/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/agent-commissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agent-commissions">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/agent-commissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/app-customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/app-customers">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/app-customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/app-invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/app-invoices">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/app-invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/app-payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/app-payments">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/app-payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/app/configs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/app/configs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/app/configs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/app/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/app/coupons">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/app/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/app/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/app/tracking-purchases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/app/tracking-purchases">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/app/tracking-purchases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/app/ulip-api-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/app/ulip-api-test">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/app/ulip-api-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/arrival-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/arrival-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/arrival-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/call-routing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/call-routing">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/call-routing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/channel-partners/customer/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/channel-partners/customer/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/channel-partners/customer/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/channel-partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/channel-partners">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/channel-partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/channel-partners/partner/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/channel-partners/partner/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/channel-partners/partner/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/chat-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/chat-logs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/chat-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/claims/capture-links/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/claims/capture-links">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/claims/capture-links/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/claims/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/claims">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/claims/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/crm/user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/user">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/crm/user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/field-operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/field-operations">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/field-operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/fssai-leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/fssai-leads">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/fssai-leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/growth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/growth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/impersonate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/impersonate">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/impersonate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/insurance-forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/insurance-forms">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/insurance-forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/insurance-learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/insurance-learning">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/insurance-learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/insurance-payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/insurance-payments">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/insurance-payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/invoice-approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invoice-approvals">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/invoice-approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/invoice-tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invoice-tracking">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/invoice-tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/invoices/bin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invoices/bin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/invoices/bin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ledger">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/operations/fasttag/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operations/fasttag">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/operations/fasttag/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/operations/tracking-children/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operations/tracking-children">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/operations/tracking-children/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/pdf-editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pdf-editor">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/pdf-editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/quick-details/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/quick-details/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/quick-details/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/quick-details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/quick-details">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/quick-details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/team-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/team-logs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/team-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tracking">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/trips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trips">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/trips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/agent/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/agent/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/agent/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/agent/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/channel-partner/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/channel-partner/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/channel-partner/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/claim-documents/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/claim-documents/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/claim-documents/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/claim/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/claim/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/claim/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/claims/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/claims">> = Specific
  const handler = {} as typeof import("../../../src/app/claims/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/consent-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consent-preview">> = Specific
  const handler = {} as typeof import("../../../src/app/consent-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../../src/app/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/crm/user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm/user">> = Specific
  const handler = {} as typeof import("../../../src/app/crm/user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/customer/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/wallet">> = Specific
  const handler = {} as typeof import("../../../src/app/customer/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/daily-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/daily-log">> = Specific
  const handler = {} as typeof import("../../../src/app/daily-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/docs/mou/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/mou">> = Specific
  const handler = {} as typeof import("../../../src/app/docs/mou/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../../src/app/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/field/add-lead/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/field/add-lead">> = Specific
  const handler = {} as typeof import("../../../src/app/field/add-lead/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/field/meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/field/meetings">> = Specific
  const handler = {} as typeof import("../../../src/app/field/meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/field/my-leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/field/my-leads">> = Specific
  const handler = {} as typeof import("../../../src/app/field/my-leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/field/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/field">> = Specific
  const handler = {} as typeof import("../../../src/app/field/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/field/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/field/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/field/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../../src/app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/insurance-dekho/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insurance-dekho">> = Specific
  const handler = {} as typeof import("../../../src/app/insurance-dekho/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/insurance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insurance">> = Specific
  const handler = {} as typeof import("../../../src/app/insurance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/know-your-vehicle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/know-your-vehicle">> = Specific
  const handler = {} as typeof import("../../../src/app/know-your-vehicle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../../src/app/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/m/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/m/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/mandi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mandi">> = Specific
  const handler = {} as typeof import("../../../src/app/mandi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/my-insurance-forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-insurance-forms">> = Specific
  const handler = {} as typeof import("../../../src/app/my-insurance-forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/papers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/papers">> = Specific
  const handler = {} as typeof import("../../../src/app/papers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../../src/app/partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pay/[shortCode]/done/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pay/[shortCode]/done">> = Specific
  const handler = {} as typeof import("../../../src/app/pay/[shortCode]/done/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pay/[shortCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pay/[shortCode]">> = Specific
  const handler = {} as typeof import("../../../src/app/pay/[shortCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pay">> = Specific
  const handler = {} as typeof import("../../../src/app/pay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/payment/failed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/failed">> = Specific
  const handler = {} as typeof import("../../../src/app/payment/failed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/payment/pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/pending">> = Specific
  const handler = {} as typeof import("../../../src/app/payment/pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/payment/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/success">> = Specific
  const handler = {} as typeof import("../../../src/app/payment/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../src/app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/promo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/promo">> = Specific
  const handler = {} as typeof import("../../../src/app/promo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/quick-details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quick-details">> = Specific
  const handler = {} as typeof import("../../../src/app/quick-details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/refund-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refund-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/refund-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/session-expired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/session-expired">> = Specific
  const handler = {} as typeof import("../../../src/app/session-expired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../../src/app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tata-uat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tata-uat">> = Specific
  const handler = {} as typeof import("../../../src/app/tata-uat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms-and-conditions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-and-conditions">> = Specific
  const handler = {} as typeof import("../../../src/app/terms-and-conditions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tracking/live-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tracking/live-map">> = Specific
  const handler = {} as typeof import("../../../src/app/tracking/live-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tracking">> = Specific
  const handler = {} as typeof import("../../../src/app/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/transporter/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transporter/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/transporter/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/whatsapp-chats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/whatsapp-chats">> = Specific
  const handler = {} as typeof import("../../../src/app/whatsapp-chats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/agent/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/agent">> = Specific
  const handler = {} as typeof import("../../../src/app/agent/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/crm/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../../src/app/crm/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/field/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/field">> = Specific
  const handler = {} as typeof import("../../../src/app/field/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/leads/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../../src/app/leads/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/whatsapp-chats/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/whatsapp-chats">> = Specific
  const handler = {} as typeof import("../../../src/app/whatsapp-chats/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
